stages:
    - setup
    - test
    - build
    - release

image: node:lts-alpine

variables:
    GIT_STRATEGY: fetch

setup:modules:
    stage: setup
    script:
        - npx lerna bootstrap
    artifacts:
        name: "node_modules_$CI_COMMIT_REF_NAME"
        paths:
            - packages/**/node_modules
        expire_in: 1 hour

test:lint:
    stage: test
    script: npx lerna run lint

test:test:
    stage: test
    script: npx lerna run test

build:package:
    stage: build
    script: npx lerna run build
    artifacts:
        name: "dist_$CI_COMMIT_REF_NAME"
        paths:
            - packages/**/dist
        expire_in: 1 hour

release:package:
    only:
        - tags
    stage: release
    script:
        - npm config set registry http:$NPM_REGISTRY
        - echo "${NPM_REGISTRY}:_authToken=${NPM_TOKEN}">.npmrc
        - lerna publish
