stages:
- test
- build

image: node:alpine

variables:
    GIT_STRATEGY: fetch

before_script:
    -  yarn install

test:lint:
    stage: test
    script: yarn lint

test:test:
    stage: test
    script: yarn test

build:package:
    stage: build
    script: yarn build
