stages:
    - setup
    - test
    - build
    - release

image: node:alpine

variables:
    GIT_STRATEGY: fetch

setup:modules:
    stage: setup
    script: npm install
    artifacts:
        paths:
            - node_modules
        expire_in: 1 hour

test:lint:
    stage: test
    script: npm run lint

test:test:
    stage: test
    script: npm run test

build:package:
    stage: build
    script: npm run build
    artifacts:
        paths:
            - dist
        expire_in: 1 hour

release:package:
    only:
        - tags
    stage: release
    script:
        - npm config set registry http:$NPM_REGISTRY
        - echo "${NPM_REGISTRY}:_authToken=${NPM_TOKEN}">.npmrc
        - npm --no-git-tag-version --allow-same-version version $CI_COMMIT_TAG
        - npm publish
