stages:
    - setup
    - test
    - build
    - release

image: node:18-alpine

variables:
    GIT_STRATEGY: fetch

setup:modules:
    stage: setup
    script:
        - npm ci
    artifacts:
        name: "node_modules_$CI_COMMIT_REF_NAME"
        paths:
            - node_modules
        expire_in: 1 hour

test:lint:
    stage: test
    script: npm run check:code-style -ws

test:test:
    stage: test
    script: npm test -ws

build:package:
    stage: build
    script: npm run build -ws
    artifacts:
        name: "dist_$CI_COMMIT_REF_NAME"
        paths:
            - packages/**/dist
        expire_in: 1 hour

release:package:
    only:
        - tags
    stage: release
    script:
        - npx lerna publish from-package --yes
