name: Release and Publish Packages

on:
    push:
        branches:
            - '**'
        tags:
            - v*

jobs:
    test:
        name: Run unit tests
        runs-on: ubuntu-latest
        steps:
            - name: Check out repository
              uses: actions/checkout@v4
            - name: Setup NodeJS
              uses: actions/setup-node@v3
              with:
                  node-version: 18
            - name: Install node dependencies
              run: npm ci
            - name: Run code-style
              run: npm run check:code-style -ws
            - name: Run tests
              run: npm test -ws

    release:
        name: Create release and publish
        needs: test
        if: github.repository == 'brainbits/node-logger' && github.ref_type == 'tag'
        runs-on: ubuntu-latest
        steps:
            - name: Check out repository
              uses: actions/checkout@v4
            - name: Setup NodeJS
              uses: actions/setup-node@v3
              with:
                  node-version: 18
                  registry-url: https://registry.npmjs.org/
            - name: Install node dependencies
              run: npm ci
            - name: Build
              run: npm run build -ws
            - name: Release and publish using lerna with conventional commits
              env:
                  NODE_AUTH_TOKEN: ${{secrets.npm_token}}
              run: npx lerna publish from-package --yes
